sudo : true
language : java

install:
  - curl https://ayera.dl.sourceforge.net/project/jflex/jflex/1.6.1/jflex-1.6.1.tar.gz --output jflex-1.6.1.tar.gz
  - echo "921496537b70f80cdd7037087a34766c3e4adbf5  jflex-1.6.1.tar.gz" | sha1sum -c
  - sudo tar -C /usr/share -xvzf jflex-1.6.1.tar.gz
  - sudo ln -s /usr/share/jflex-1.6.1/bin/jflex /usr/bin/jflex
  - rm -rf jflex-1.6.1.tar.gz

script : make
after_script : make fclean

stages:
  - Base Compilation
  - Unit Test
  - Final

jobs:
  include:
    - os: linux
      jdk: oraclejdk8
      stage: Base Compilation
      env:
         - NAME="Linux"
    - os: linux
      jdk: oraclejdk9
      stage: Base Compilation
      env:
         - NAME="Linux"
    - os: linux
      jdk: openjdk8
      stage: Base Compilation
      env:
         - NAME="Linux"
    - os: linux
      jdk: oraclejdk8
      stage: Unit Test
      script : make basic_test
      env :
         - NAME="Basic test"
    - os: linux
      jdk: oraclejdk9
      stage: Unit Test
      script : make basic_test
      env :
         - NAME="Basic test"
    - os: linux
      jdk: openjdk8
      stage: Unit Test
      script : make basic_test
      env :
         - NAME="Basic test"
    - os: linux
      jdk: oraclejdk8
      stage: Unit Test
      script : make sys_test
      env :
         - NAME="Sys test"
    - os: linux
      jdk: oraclejdk9
      stage: Unit Test
      script : make sys_test
      env :
         - NAME="Sys test"
    - os: linux
      jdk: openjdk8
      stage: Unit Test
      script : make sys_test
      env :
         - NAME="Sys test"
    - os: linux
      jdk: oraclejdk8
      stage: Unit Test
      script : make bonus_test
      env :
         - NAME="Bonus test"
    - os: linux
      jdk: oraclejdk9
      stage: Unit Test
      script : make bonus_test
      env :
         - NAME="Bonus test"
    - os: linux
      jdk: openjdk8
      stage: Unit Test
      script : make bonus_test
      env :
         - NAME="Bonus test"
    - os: linux
      jdk: oraclejdk8
      stage: Final
      script : make test
      env :
         - NAME="Full Build All"
    - os: linux
      jdk: oraclejdk9
      stage: Final
      script : make test
      env :
         - NAME="Full Build All"
    - os: linux
      jdk: oraclejdk8
      stage: Final
      script : make test
      env :
         - NAME="Full Build All"
