sudo : true
language : java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

install:
  - curl http://jflex.de/release/jflex-1.6.1.tar.gz --output jflex-1.6.1.tar.gz
  - sudo tar -C /usr/share -xvzf jflex-1.6.1.tar.gz
  - sudo ln -s /usr/share/jflex-1.6.1/bin/jflex /usr/bin/jflex

script : make
after_script : make fclean

matrix:
  include:
    - os: linux
      env:
         - NAME="Single Compile test"
    - os: linux
      script : make basic_test
      env :
         - NAME="Full Build All"
    - os: linux
      script : make sys_test
      env :
         - NAME="Full Build All"
    - os: linux
      script : make bonus_test
      env :
         - NAME="Full Build All"
    - os: linux
      script : make test
      env :
         - NAME="Full Build All"
